In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([(1.3,2,3,),(4,5,6)],dtype=float)
print(b)

[[1.3 2.  3. ]
 [4.  5.  6. ]]


In [6]:
#1. SUM
a.sum()

6

In [7]:
b.sum()

21.3

In [8]:
#2. MIN FUNCTION
a.min()

1

In [9]:
b.min()

1.3

In [10]:
#3. MAX FUNCTION


In [11]:
b.max(axis=1)

array([3., 6.])

In [12]:
b.max(axis=0)

array([4., 5., 6.])

In [13]:
#CUMULATIVE SUM

In [14]:
b.max(axis=0)

array([[1.3, 2. , 3. ],
       [5.3, 7. , 9. ]])

In [15]:
b.max(axis=1)

array([3., 6.])

In [20]:
#4. MEAN

In [21]:
a.mean()

2.0

In [24]:
b.mean()

3.5500000000000003

In [25]:
#5. median

In [26]:
np.median(a)

2.0

In [28]:
b

array([[1.3, 2. , 3. ],
       [4. , 5. , 6. ]])

In [29]:
np.median(b)

3.5

In [ ]:
#standard deviation

In [30]:
np.std(b)

1.6368160149102484