In [27]:
a=np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [28]:
b=np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [29]:
a + b 

array([ 5,  7,  9, 11, 13])

In [30]:
#BROADCASTIG WITH SCALERS(adding constant value)

a=np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [31]:
a+10  

array([10, 11, 12, 13, 14, 15])

In [32]:
a > 2 #vectorized boolean operations

array([False, False, False,  True,  True,  True])

In [33]:
x=lambda x: x**2

In [34]:
x(9)

81

In [38]:
a=lambda x,y: x+y
a(4,5)

9